"""Create role table check

Revision ID: 163aa13bfdee
Revises: afb35424a6db
Create Date: 2024-10-04 16:03:08.305559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163aa13bfdee'
down_revision = 'afb35424a6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
