"""add special requirement in animal

Revision ID: 297a4a0b1875
Revises: 7026b7aa9f0d
Create Date: 2024-10-05 03:33:19.653421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297a4a0b1875'
down_revision = '7026b7aa9f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialRequirement', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('specialRequirement')

    # ### end Alembic commands ###
