"""update add join date to employee

Revision ID: 584840b9518f
Revises: 163aa13bfdee
Create Date: 2024-10-04 16:04:34.479099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584840b9518f'
down_revision = '163aa13bfdee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
