name: CI-TEST
on: push

jobs:
  ci:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.7.1
      - name: install dependencies
        working-directory: .
        run: poetry install
      - name: Run tests
        working-directory: .
        env:
          SUPABASE_TEST_DB_URL: postgresql://testuser:testpassword@localhost:5432/testdb
          JWT_SECRET_KEY: 'YXVkaW5lIGFtZWxseQ=='
        run: poetry run pytest